// Code generated by mongen. DO NOT EDIT.
package examplesmws

import (
	alias1 "context"
	alias5 "github.com/Bo0mer/gentools/cmd/mongen/examples"
	alias2 "go.opencensus.io/stats"
	alias3 "go.opencensus.io/tag"
	alias4 "time"
)

type monitoringServiceMixedCtxMultiMethod struct {
	next        alias5.ServiceMixedCtxMultiMethod
	totalOps    *alias2.Int64Measure
	failedOps   *alias2.Int64Measure
	opsDuration *alias2.Float64Measure
}

// NewMonitoringServiceMixedCtxMultiMethod creates new monitoring middleware.
func NewMonitoringServiceMixedCtxMultiMethod(next alias5.ServiceMixedCtxMultiMethod, totalOps *alias2.Int64Measure, failedOps *alias2.Int64Measure, opsDuration *alias2.Float64Measure) alias5.ServiceMixedCtxMultiMethod {
	return &monitoringServiceMixedCtxMultiMethod{next, totalOps, failedOps, opsDuration}
}
func (m *monitoringServiceMixedCtxMultiMethod) DoWork(arg1 int, arg2 string) (string, error) {
	ctx := alias1.Background()
	tagKey, _ := alias3.NewKey("operation")
	ctx, _ = alias3.New(ctx, alias3.Insert(tagKey, "do_work"))
	alias2.Record(ctx, m.totalOps.M(1))
	start := alias4.Now()
	result1, result2 := m.next.DoWork(arg1, arg2)
	alias2.Record(ctx, m.opsDuration.M(alias4.Since(start).Seconds()))
	if result2 != nil {
		alias2.Record(ctx, m.failedOps.M(1))
	}
	return result1, result2
}
func (m *monitoringServiceMixedCtxMultiMethod) DoWorkCtx(arg1 alias1.Context, arg2 int, arg3 string) (string, error) {
	ctx := arg1
	tagKey, _ := alias3.NewKey("operation")
	ctx, _ = alias3.New(ctx, alias3.Insert(tagKey, "do_work_ctx"))
	alias2.Record(ctx, m.totalOps.M(1))
	start := alias4.Now()
	result1, result2 := m.next.DoWorkCtx(arg1, arg2, arg3)
	alias2.Record(ctx, m.opsDuration.M(alias4.Since(start).Seconds()))
	if result2 != nil {
		alias2.Record(ctx, m.failedOps.M(1))
	}
	return result1, result2
}
