// Code generated by mongen. DO NOT EDIT.
package examplesmws

import (
	alias4 "context"
	alias1 "github.com/Bo0mer/gentools/cmd/mongen/examples"
	alias2 "github.com/go-kit/kit/metrics"
	alias3 "time"
)

type monitoringServiceCtx struct {
	next        alias1.ServiceCtx
	totalOps    alias2.Counter
	failedOps   alias2.Counter
	opsDuration alias2.Histogram
}

// NewMonitoringServiceCtx creates new monitoring middleware.
func NewMonitoringServiceCtx(next alias1.ServiceCtx, totalOps alias2.Counter, failedOps alias2.Counter, opsDuration alias2.Histogram) alias1.ServiceCtx {
	return &monitoringServiceCtx{next, totalOps, failedOps, opsDuration}
}
func (m *monitoringServiceCtx) DoWork(arg1 alias4.Context, arg2 int, arg3 string) (string, error) {
	m.totalOps.With("operation", "do_work").Add(1)
	_start := alias3.Now()
	result1, result2 := m.next.DoWork(arg1, arg2, arg3)
	m.opsDuration.With("operation", "do_work").Observe(alias3.Since(_start).Seconds())
	if result2 != nil {
		m.failedOps.With("operation", "do_work").Add(1)
	}
	return result1, result2
}
