// Code generated by mongen. DO NOT EDIT.
package examplesmws

import (
	alias1 "github.com/Bo0mer/gentools/cmd/mongen/examples"
	alias2 "github.com/go-kit/kit/metrics"
	alias3 "time"
)

type monitoringServiceNoCtx struct {
	next        alias1.ServiceNoCtx
	totalOps    alias2.Counter
	failedOps   alias2.Counter
	opsDuration alias2.Histogram
}

// NewMonitoringServiceNoCtx creates new monitoring middleware.
func NewMonitoringServiceNoCtx(next alias1.ServiceNoCtx, totalOps alias2.Counter, failedOps alias2.Counter, opsDuration alias2.Histogram) alias1.ServiceNoCtx {
	return &monitoringServiceNoCtx{next, totalOps, failedOps, opsDuration}
}
func (m *monitoringServiceNoCtx) DoWork(arg1 int, arg2 string) (string, error) {
	m.totalOps.With("operation", "do_work").Add(1)
	_start := alias3.Now()
	result1, result2 := m.next.DoWork(arg1, arg2)
	m.opsDuration.With("operation", "do_work").Observe(alias3.Since(_start).Seconds())
	if result2 != nil {
		m.failedOps.With("operation", "do_work").Add(1)
	}
	return result1, result2
}
